title: Jędrzej Miarecki
logo: /assets/img/logo.png
description: >
  Mathematician.<br>
  Bachelor of Mathematics (University of Wrocław).<br>  
  Student of Mathematics (Master's) at University of Opole.<br><br>  
  My mathematical interests are in number theory and cryptography.<br><br>  
  
  <a href="https://www.linkedin.com/in/jmiarecki/" target="_blank">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
mathjax: true
