title: Jędrzej Miarecki
logo: /assets/img/logo.png
description: >
  Mathematician  
  Bachelor of Mathematics (University of Wrocław)  
  Student of Mathematics (Master's) at University of Opole  
  
  My mathematical interests are in number theory and cryptography.  
  
  <a href="https://www.linkedin.com/in/jmiarecki/" target="_blank">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
